## Throughput comparison Ingress From EBI to DFN and Telekom

- Import the data

```{r, echo=F}
(throughput <- read.csv(file='ingess-from-ebi-to-dfn-and-telekom.csv', stringsAsFactors=FALSE))
```

- Prepare data for ggplot

```{r, echo=F, warning=F, message=F}
library(reshape2)
throughput_plot <- melt(throughput)
colnames(throughput_plot) <- c("Provider", "Throughput")
```

- Combined histogram

```{r, message=F, warning=F, echo=F, fig.width=9}
library(ggplot2)

p <- ggplot(throughput_plot, aes(x=Throughput, fill=Provider))
p <- p + geom_histogram(alpha=1, binwidth = 0.04)
p <- p + scale_fill_manual(values=c("#00599d", "#bf0e88"))
p <- p + scale_x_continuous(breaks=seq(5,10,0.5))
p <- p + theme(axis.text.x=element_text(face="bold")) 
p <- p + theme(axis.text.y=element_text(face="bold")) 
p
```

- Combined density plot

```{r, echo=F, fig.width=9}
p <- ggplot(throughput_plot, aes(x=Throughput, fill=Provider))
p <- p + geom_density()
p <- p + scale_fill_manual(values=c("#00599d", "#bf0e88"))
p <- p + scale_x_continuous(breaks=seq(0,12,0.5))
p <- p + theme(axis.text.x=element_text(face="bold")) 
p <- p + theme(axis.text.y=element_text(face="bold")) 
p <- p + labs(
  title="Throughput Report Ingress",
  subtitle="Source: emblhd-ebihost.ebi.ac.uk (JANET), Destination: perfsonar1.embl.de (DFN) & perfsonar2.embl.de (Telekom)",
  x="Throughput (Gbps)",
  y="Density")
p
```