---
title: "Network Measurements"
author:
- Beatriz Serrano Solano - https://github.com/beatrizserrano
- Carlos Fernandez San Millan - https://github.com/Cormite
abstract: |
  Project written in R to produce semantical and sensible graphical representation of network data collected with iperf3 and mtr.
   
  Beatriz Serrano Solano: R code.
  Carlos Fernandez San Millan: Network data collection.
  Project home: https://github.com/cormite/Network-Measurements
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

## Throughput Report - DFN vs Telekom

### Ingress & Egress EMBL Outstations

The following graphs represent the throughput achieved from and to EMBL (Heidelberg) and various EMBL outstations.

```{r, message=F, warning=F, echo=F, fig.width=9}
library(reshape2)
library(ggplot2)
metadata <- read.csv(file=file.path(getwd(), "data/metadata/throughput-metadata.csv"), stringsAsFactors=FALSE, sep = ",")
for(i in 1:nrow(metadata)) {
  dataset <- metadata[i,]
  #print (dataset)
  throughput <- read.csv(file = paste0("data/throughput/",dataset$FileName), stringsAsFactors = FALSE)
  throughput_plot <- melt(throughput)
  colnames(throughput_plot) <- c("Provider", "Throughput")
  
  min <- min(throughput_plot$Throughput)
  max <- max(throughput_plot$Throughput)
  jump_size <- round((max - min) / 20, digits = 1)
  
  
  p <- ggplot(throughput_plot, aes(x = Throughput, fill = Provider))
  #p <- p + geom_histogram(alpha=1, binwidth = 0.04)
  p <- p + geom_density(alpha = 0.3)
  p <- p + scale_fill_manual(values = c("#00599d", "#bf0e88"))
  p <- p + scale_x_continuous(breaks = seq(min, max, jump_size))
  p <- p + theme(axis.text.x = element_text(face = "bold"))
  p <- p + theme(axis.text.y = element_text(face = "bold"))
  p <- p + labs(
    title = paste0("Throughput Report"),
    subtitle = paste0("Source: ", dataset$Source, " \nDestination: ", dataset$Destination), x = "Throughput (Gbps)"
  )
  print(p)
}
```



## Traceroute and latency

```{r, message=F, warning=F, echo=F, fig.width=9}
metadata <- read.csv(file=file.path(getwd(), "data/metadata/latency-metadata.csv"), stringsAsFactors=FALSE, sep = ",")
for(i in 1:nrow(metadata)) {
  dataset <- metadata[i,]
  #print (dataset)
  mtr <- read.csv(file = paste0("data/traceroute-and-latency/",dataset$FileName), header=T, stringsAsFactors = FALSE)
  
  # Rename "???" entries to avoid duplicates
  #(mtr[mtr$Ip=="???",]$Ip <- paste0("Hop__", mtr[mtr$Ip=="???",]$Hop))
  
  mtr <- mtr[order(-mtr$Hop),]
  mtr$Ip <- factor(mtr$Ip, levels=mtr$Ip)
  
  min <- min(mtr$Best)
  max <- max(mtr$Wrst)
  jump_size <- round((max - min) / 20, digits = 1)
  
  # Plot
  p <- ggplot(mtr, aes(x=Ip, y=Avg))
  p <- p + geom_line(size=1)
  p <- p + geom_errorbar(aes(ymin=Avg-StDev, ymax=Avg+StDev), width=0.05, position=position_dodge(0.05))
  p <- p + geom_point(size=3, colour="darkred")
  p <- p + labs(title="Average and Standard Deviation of the latency",
                subtitle = paste0("Source: ", dataset$Source, " \nDestination: ", dataset$Destination),
                x="Hostname / IP",
                y="Latency (ms)")
  p <- p + scale_y_continuous(breaks=seq(min,max,jump_size))
  p <- p + theme(axis.text.x=element_text(face="bold")) 
  p <- p + theme(axis.text.y=element_text(face="bold"))
  p <- p + coord_flip()
  print(p)
}

```



